name: Build and Deploy

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install

      - name: Install Expo CLI and EAS CLI
        run: |
          npm install -g expo-cli
          npm install -g eas-cli

      - name: Log in to EAS CLI
        env:
          EAS_EMAIL: ${{ secrets.EAS_EMAIL }}
          EAS_PASSWORD: ${{ secrets.EAS_PASSWORD }}
        run: |
          echo "spawn eas login" > script.exp
          echo "expect \"?Username or email address:\"" >> script.exp
          echo "send \"$EAS_EMAIL\n\"" >> script.exp
          echo "expect \"?Password:\"" >> script.exp
          echo "send \"$EAS_PASSWORD\n\"" >> script.exp
          echo "interact" >> script.exp
          expect script.exp
      - name: Build Expo project with EAS
        run:  eas build -p android --profile preview

